# Generated by Django 4.2.20 on 2025-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("response_1", models.TextField()),
                ("response_2", models.TextField()),
                ("response_3", models.TextField()),
                ("scoring_result", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
